import type { ResourceAction } from "@/features/rbac/helpers/rbac-core";
import type { AssistantWorkflowPayload, AssistantWorkflowStepPayload } from "../types/assistant";

export type AssistantWorkflowRequirement = {
  resource: string;
  action: ResourceAction;
};

export type AssistantWorkflowDefinition = AssistantWorkflowPayload & {
  faqNumber: number;
  aliases: string[];
  requiredPages: string[];
  requiredCapabilities: AssistantWorkflowRequirement[];
  iconKey: string;
  steps: Required<AssistantWorkflowStepPayload>[];
};

type WorkflowInput = {
  faqNumber: number;
  slug: string;
  title: string;
  aliases: string[];
  route: string;
  actionLabel: string;
  iconKey: string;
  requiredPages?: string[];
  requiredCapabilities: AssistantWorkflowRequirement[];
  steps: Array<{ title: string; description: string }>;
};

function sourceAnchor(title: string) {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-");
}

function workflow(input: WorkflowInput): AssistantWorkflowDefinition {
  const id = `faq-q${String(input.faqNumber).padStart(2, "0")}-${input.slug}`;
  return {
    id,
    faqNumber: input.faqNumber,
    title: input.title,
    aliases: input.aliases,
    requiredPages: input.requiredPages ?? [input.route],
    requiredCapabilities: input.requiredCapabilities,
    route: input.route,
    actionLabel: input.actionLabel,
    sourceRef: `docs/help/faq.md#q${input.faqNumber}-${sourceAnchor(input.title)}`,
    iconKey: input.iconKey,
    steps: input.steps.map((step, index) => ({
      id: `${id}-step-${index + 1}`,
      title: step.title,
      description: step.description,
      route: input.route,
      actionLabel: input.actionLabel,
      iconKey: input.iconKey,
    })),
  };
}

export const FAQ_WORKFLOWS: AssistantWorkflowDefinition[] = [
  workflow({
    faqNumber: 1,
    slug: "add-product",
    title: "Bagaimana cara menambahkan produk baru ke katalog toko?",
    aliases: ["tambah produk", "menambahkan produk baru", "buat produk baru", "input produk katalog", "harga agen produk"],
    route: "/products",
    actionLabel: "Buka Produk",
    iconKey: "package",
    requiredCapabilities: [{ resource: "product", action: "create" }],
    steps: [
      { title: "Buka katalog produk", description: "Masuk ke sidebar Katalog, lalu buka halaman Produk." },
      { title: "Mulai tambah produk", description: "Klik tombol Tambah Produk di kanan atas halaman." },
      { title: "Isi data utama", description: "Lengkapi nama produk, SKU unik, kategori, harga jual, Harga Agen atau Harga Dinas bila perlu, stok awal, satuan, dan batas minimum stok." },
      { title: "Tambahkan varian bila perlu", description: "Jika barang punya unit pecahan, tambahkan varian unit terkecil beserta SKU, barcode, dan harga jualnya." },
      { title: "Simpan produk", description: "Periksa ulang isian, lalu klik Simpan. Pak Teladan hanya membuka halaman, tidak mengisi atau menyimpan form otomatis." },
    ],
  }),
  workflow({
    faqNumber: 2,
    slug: "change-product-price",
    title: "Bagaimana cara mengubah harga jual produk agar tercatat di riwayat?",
    aliases: ["ubah harga produk", "ganti harga jual", "riwayat harga", "ubah harga jual produk", "ubah harga agen", "ubah harga dinas"],
    route: "/products",
    actionLabel: "Buka Produk",
    iconKey: "dollar-sign",
    requiredCapabilities: [{ resource: "product", action: "update" }],
    steps: [
      { title: "Buka daftar produk", description: "Masuk ke halaman Produk dan temukan produk yang harganya akan diubah." },
      { title: "Pilih Ubah Harga", description: "Gunakan tombol aksi Ubah Harga pada baris produk untuk perubahan cepat yang tercatat di Riwayat Harga." },
      { title: "Isi harga baru", description: "Masukkan nominal harga jual, HPP, Harga Dinas, atau Harga Agen pada modal yang muncul, lalu simpan jika sudah benar." },
      { title: "Gunakan Edit untuk detail penuh", description: "Jika perlu mengubah data produk lain, buka aksi Edit pada baris produk." },
    ],
  }),
  workflow({
    faqNumber: 3,
    slug: "customer-special-pricing",
    title: "Bagaimana cara mengatur harga khusus/diskon bagi grup pelanggan?",
    aliases: ["harga khusus pelanggan", "diskon agen", "harga agen", "harga dinas", "harga pelanggan industri"],
    route: "/products",
    actionLabel: "Buka Harga Khusus",
    iconKey: "badge-percent",
    requiredCapabilities: [{ resource: "product", action: "update" }],
    steps: [
      { title: "Buka Harga Khusus", description: "Masuk ke halaman Produk, lalu buka bagian Harga Khusus. Fitur ini biasanya dibatasi untuk OWNER." },
      { title: "Pilih tipe pelanggan", description: "Tentukan grup pelanggan seperti UMUM, AGEN, INDUSTRI, atau PEMERINTAH. Untuk AGEN, Harga Agen di produk dipakai dulu jika tersedia." },
      { title: "Pilih kategori dan mode", description: "Pilih kategori produk, lalu tentukan mode Diskon Persen atau Diskon Rupiah." },
      { title: "Simpan aturan", description: "Isi nilai diskon dan simpan. Aturan akan dipakai saat kasir memilih pelanggan dengan tipe tersebut." },
    ],
  }),
  workflow({
    faqNumber: 4,
    slug: "bulk-product-import",
    title: "Bagaimana cara mengimpor data produk atau stok massal lewat Excel?",
    aliases: ["import produk excel", "import stok excel", "bulk product import", "unggah produk massal", "import harga agen", "import kode supplier produk"],
    route: "/products",
    actionLabel: "Buka Import Produk",
    iconKey: "file-spreadsheet",
    requiredCapabilities: [{ resource: "product", action: "create" }, { resource: "inventory", action: "update" }],
    steps: [
      { title: "Buka Fitur Import", description: "Di halaman Pusat Produk, klik tombol dropdown Import di kanan atas." },
      { title: "Pilih tipe import", description: "Pilih Import Bulk Products untuk katalog atau Import Bulk Stock untuk kuantitas stok." },
      { title: "Unggah Excel", description: "Pilih file .xlsx dari perangkat, lalu lakukan pemetaan kolom jika nama kolom berbeda. Kolom opsional termasuk Harga Agen, Harga Dinas, dan Kode Supplier." },
      { title: "Periksa pratinjau", description: "Cek Harga Agen, Harga Dinas, kode supplier, dan keputusan baris pada pratinjau sebelum menyelesaikan import. Import berjalan di antrean background; pantau progres, lalu gunakan Coba Lagi jika antrean belum berhasil dimulai." },
    ],
  }),
  workflow({
    faqNumber: 5,
    slug: "stock-group",
    title: "Bagaimana cara mengatur Grup Stok (Stock Group)?",
    aliases: ["atur grup stok", "stock group", "gabungkan stok produk", "bulk stock group"],
    route: "/products",
    actionLabel: "Buka Grup Stok",
    iconKey: "boxes",
    requiredCapabilities: [{ resource: "product", action: "update" }],
    steps: [
      { title: "Buka aktivitas grup", description: "Masuk ke tab Aktivitas Grup di halaman Pusat Produk." },
      { title: "Mulai pengaturan", description: "Klik Atur Grup Stok atau buka Bulk Stock Group dari menu import." },
      { title: "Pilih produk utama", description: "Tentukan produk utama dan tambahkan produk anggota yang berbagi stok fisik." },
      { title: "Simpan grup", description: "Simpan pengaturan agar mutasi dan pemakaian grup stok tercatat di aktivitas." },
    ],
  }),
  workflow({
    faqNumber: 6,
    slug: "pos-sale",
    title: "Bagaimana alur memproses transaksi penjualan langsung di kasir?",
    aliases: ["proses transaksi kasir", "jualan di POS", "bayar di kasir", "alur pos"],
    route: "/pos",
    actionLabel: "Buka Kasir",
    iconKey: "shopping-cart",
    requiredCapabilities: [{ resource: "transaction", action: "create" }],
    steps: [
      { title: "Pastikan shift aktif", description: "Buka shift kasir terlebih dahulu sebelum memproses transaksi." },
      { title: "Pilih item", description: "Cari produk atau layanan, pilih varian jika ada, lalu masukkan ke keranjang." },
      { title: "Periksa keranjang", description: "Atur kuantitas atau hapus item yang tidak sesuai, lalu klik Bayar." },
      { title: "Isi pembayaran", description: "Pilih pelanggan, sales bila perlu, metode pembayaran, status Lunas atau DP, dan tipe transaksi." },
      { title: "Konfirmasi dan cetak", description: "Klik Konfirmasi Bayar atau Bayar DP, lalu cetak struk bila diperlukan." },
    ],
  }),
  workflow({
    faqNumber: 7,
    slug: "approve-pending-transaction",
    title: "Bagaimana cara menyetujui transaksi Pending yang dikirim sales lapangan?",
    aliases: ["setujui transaksi pending", "approval transaksi sales", "transaksi pending", "approve transaksi"],
    route: "/history",
    actionLabel: "Buka Riwayat",
    iconKey: "clipboard-check",
    requiredCapabilities: [{ resource: "transaction.approve", action: "update" }],
    steps: [
      { title: "Buka Riwayat", description: "Masuk ke Riwayat Transaksi dan gunakan filter Pending untuk melihat transaksi yang menunggu persetujuan." },
      { title: "Pilih aksi", description: "Klik Setujui atau Tolak pada baris transaksi, atau gunakan menu tiga titik." },
      { title: "Isi modal persetujuan", description: "Pilih Bayar Instan atau Bayar Nanti, lalu lengkapi metode dan nominal pembayaran." },
      { title: "Finalisasi keputusan", description: "Klik Setujui untuk memotong stok dan memfinalisasi, atau Tolak untuk membatalkan transaksi pending." },
    ],
  }),
  workflow({
    faqNumber: 8,
    slug: "create-delivery-order",
    title: "Bagaimana cara membuat Surat Jalan Pengiriman barang ke pelanggan?",
    aliases: ["buat surat jalan", "cetak surat jalan", "delivery order", "pengiriman barang pelanggan"],
    route: "/history",
    actionLabel: "Buka Riwayat",
    iconKey: "truck",
    requiredCapabilities: [{ resource: "surat_jalan", action: "create" }],
    steps: [
      { title: "Cari transaksi", description: "Temukan transaksi Lunas atau DP yang memiliki produk fisik di halaman Riwayat." },
      { title: "Buka aksi Surat Jalan", description: "Klik menu tiga titik pada baris transaksi, lalu pilih Cetak Surat Jalan." },
      { title: "Buat dokumen", description: "Klik Buat Surat Jalan atau Buat Surat Jalan Baru jika sudah ada pengiriman sebelumnya." },
      { title: "Isi detail pengiriman", description: "Masukkan jumlah barang, kurir, pengemudi, pelat kendaraan, penerima, dan catatan bila perlu." },
      { title: "Simpan dokumen", description: "Proses Surat Jalan agar tersimpan dan siap dicetak sebagai bukti pengiriman." },
    ],
  }),
  workflow({
    faqNumber: 9,
    slug: "print-invoice",
    title: "Bagaimana cara mencetak invoice atau struk transaksi?",
    aliases: ["cetak invoice", "cetak struk", "print invoice", "struk transaksi"],
    route: "/history",
    actionLabel: "Buka Riwayat",
    iconKey: "printer",
    requiredCapabilities: [{ resource: "transaction", action: "read" }],
    steps: [
      { title: "Pilih jalur cetak", description: "Cetak dari POS setelah pembayaran selesai, atau dari Riwayat untuk transaksi lama." },
      { title: "Buka transaksi", description: "Di Riwayat, cari dan klik baris transaksi yang ingin dicetak." },
      { title: "Gunakan tombol cetak", description: "Pada panel detail, klik ikon printer atau tombol Cetak Invoice/Struk." },
    ],
  }),
  workflow({
    faqNumber: 10,
    slug: "upload-receipt-proof",
    title: "Bagaimana cara mengunggah foto nota atau bukti transaksi?",
    aliases: ["unggah bukti transaksi", "upload nota", "foto struk", "url lampiran"],
    route: "/history",
    actionLabel: "Buka Riwayat",
    iconKey: "image",
    requiredCapabilities: [{ resource: "transaction", action: "update" }],
    steps: [
      { title: "Unggah gambar eksternal", description: "Buka layanan unggah gambar seperti prnt.sc, lalu unggah foto bukti atau nota." },
      { title: "Salin tautan", description: "Setelah upload selesai, salin link gambar yang dihasilkan." },
      { title: "Tempel di aplikasi", description: "Kembali ke modal POS yang membutuhkan bukti, lalu tempel link pada kolom URL Lampiran." },
      { title: "Simpan lampiran", description: "Periksa pratinjau gambar jika tersedia, lalu klik Simpan." },
    ],
  }),
  workflow({
    faqNumber: 11,
    slug: "cashier-shift",
    title: "Bagaimana cara memulai dan mengakhiri shift kerja kasir?",
    aliases: ["buka shift", "tutup shift", "mulai shift kasir", "akhiri shift kasir"],
    route: "/shift",
    actionLabel: "Buka Shift Kasir",
    iconKey: "wallet",
    requiredCapabilities: [{ resource: "shift", action: "create" }, { resource: "shift", action: "update" }],
    steps: [
      { title: "Buka Shift Kasir", description: "Masuk ke menu Shift Kasir saat baru mulai kerja." },
      { title: "Isi kas awal", description: "Ketik nominal modal uang tunai awal yang ada di laci kasir." },
      { title: "Mulai shift", description: "Klik Mulai Shift agar transaksi kasir bisa berjalan." },
      { title: "Tutup shift", description: "Di akhir kerja, hitung uang fisik, isi nominal tutup laci dan catatan bila perlu." },
      { title: "Konfirmasi akhir", description: "Klik Konfirmasi Akhiri Shift untuk membandingkan kas fisik dengan catatan sistem." },
    ],
  }),
  workflow({
    faqNumber: 12,
    slug: "edit-closed-shift",
    title: "Bagaimana cara mengoreksi laporan shift kasir yang sudah ditutup?",
    aliases: ["ubah laporan shift", "koreksi shift", "edit shift tertutup", "saldo akhir shift salah"],
    route: "/shift",
    actionLabel: "Buka Shift Kasir",
    iconKey: "pencil",
    requiredCapabilities: [{ resource: "shift", action: "update" }],
    steps: [
      { title: "Buka Riwayat Shift", description: "Masuk ke tab Riwayat di halaman Shift Kasir." },
      { title: "Cari shift", description: "Temukan baris shift yang perlu dikoreksi." },
      { title: "Edit data", description: "Klik ikon pensil, sesuaikan saldo akhir atau catatan, lalu simpan." },
    ],
  }),
  workflow({
    faqNumber: 13,
    slug: "add-customer",
    title: "Bagaimana cara mendaftarkan pelanggan baru ke sistem?",
    aliases: ["tambah pelanggan", "daftar pelanggan baru", "input customer", "buat customer baru"],
    route: "/customers",
    actionLabel: "Buka Pelanggan",
    iconKey: "user-plus",
    requiredCapabilities: [{ resource: "customer", action: "create" }],
    steps: [
      { title: "Buka Pelanggan", description: "Masuk ke menu Pelanggan, lalu buka halaman Pelanggan." },
      { title: "Klik Tambah Pelanggan", description: "Gunakan tombol Tambah Pelanggan di kanan atas, atau Import Excel untuk data massal." },
      { title: "Isi profil", description: "Lengkapi nama wajib, tipe pelanggan, nomor HP, email, perusahaan, alamat, dan catatan." },
      { title: "Simpan pelanggan", description: "Periksa data, lalu klik Simpan." },
    ],
  }),
  workflow({
    faqNumber: 14,
    slug: "customer-debt-payment",
    title: "Bagaimana cara mencatat pembayaran cicilan atau pelunasan piutang pelanggan?",
    aliases: ["bayar piutang", "pelunasan piutang", "cicilan pelanggan", "bayar hutang pelanggan"],
    route: "/customers",
    actionLabel: "Buka Piutang Pelanggan",
    iconKey: "receipt",
    requiredCapabilities: [{ resource: "customer", action: "update" }],
    steps: [
      { title: "Buka tab Piutang", description: "Di halaman Pelanggan, pilih tab Piutang." },
      { title: "Pilih invoice", description: "Cari invoice yang ingin dilunasi atau dicicil, lalu klik Bayar Piutang." },
      { title: "Isi pembayaran", description: "Pilih satu atau beberapa metode pembayaran dan isi nominal untuk masing-masing metode." },
      { title: "Proses pembayaran", description: "Tambahkan catatan bila perlu, lalu klik Proses Pembayaran." },
      { title: "Alternatif dari Riwayat", description: "Untuk transaksi DP, buka detail transaksi di Riwayat dan gunakan tombol Bayar Cicilan." },
    ],
  }),
  workflow({
    faqNumber: 15,
    slug: "damaged-stock-report",
    title: "Bagaimana cara melaporkan barang rusak, hilang, atau menyusut di gudang?",
    aliases: ["lapor barang rusak", "barang hilang", "stok menyusut", "laporan kerusakan gudang"],
    route: "/inventory",
    actionLabel: "Buka Inventaris",
    iconKey: "triangle-alert",
    requiredCapabilities: [{ resource: "inventory", action: "update" }],
    steps: [
      { title: "Buka Inventaris", description: "Masuk ke halaman Inventaris dan klik menu Input / Transaksi." },
      { title: "Pilih laporan rusak", description: "Pilih opsi Laporkan Barang Rusak." },
      { title: "Isi detail", description: "Pilih produk, masukkan jumlah stok yang rusak, hilang, atau menyusut, lalu tulis alasan." },
      { title: "Submit laporan", description: "Klik Submit. Laporan akan tersimpan atau masuk proses persetujuan sesuai aturan gudang." },
    ],
  }),
  workflow({
    faqNumber: 16,
    slug: "weekly-proof-task",
    title: "Bagaimana cara menyelesaikan tugas operasional mingguan?",
    aliases: ["proof kebersihan", "tugas mingguan", "unggah kebersihan gudang", "weekly proof"],
    route: "/inventory",
    actionLabel: "Buka Tugas Inventaris",
    iconKey: "clipboard-list",
    requiredCapabilities: [{ resource: "inventory", action: "update" }],
    steps: [
      { title: "Buka tab Tugas", description: "Di halaman Inventaris, buka tab Tugas. Check In mungkin diperlukan lebih dulu." },
      { title: "Pilih tugas mingguan", description: "Temukan tugas seperti Proof Kebersihan Gudang." },
      { title: "Unggah bukti", description: "Klik tugas atau tombol aksi, unggah foto ke prnt.sc, lalu tempel link hasil upload pada form proof." },
      { title: "Submit tugas", description: "Cek pratinjau gambar, lalu klik Submit Proof agar tugas tercatat selesai." },
    ],
  }),
  workflow({
    faqNumber: 17,
    slug: "inbound-receipt",
    title: "Bagaimana cara mengajukan Penerimaan Barang dari supplier?",
    aliases: ["penerimaan barang", "inbound receipt", "barang masuk supplier", "ajukan penerimaan"],
    route: "/inventory",
    actionLabel: "Buka Penerimaan Barang",
    iconKey: "package-plus",
    requiredCapabilities: [{ resource: "inventory", action: "update" }],
    steps: [
      { title: "Buka Penerimaan Barang", description: "Di halaman Inventaris, buka tab Transaksi lalu pilih Penerimaan Barang." },
      { title: "Pilih invoice daftar belanja", description: "Klik Terima barang, lalu pilih invoice dari daftar belanja. Opsi berwarna membantu membedakan invoice yang belum dipakai, punya badge Sudah dibuat, atau sudah lengkap diterima." },
      { title: "Isi kuantitas fisik", description: "Periksa item invoice, isi jumlah barang yang benar-benar datang, dan tambahkan catatan jika ada selisih atau kondisi khusus." },
      { title: "Ajukan ke Owner", description: "Klik Ajukan ke Owner. Pengajuan belum menambah stok sampai ada keputusan dari role yang memiliki izin RBAC granular inventory.inbound_receipt.approve, inventory.inbound_receipt.reject, atau inventory.inbound_receipt.revise." },
      { title: "Tangani Perlu Revisi", description: "Jika owner memilih Minta Revisi, buka filter Perlu Revisi, klik Edit & Ajukan, perbaiki data, lalu ajukan ulang." },
    ],
  }),
  workflow({
    faqNumber: 18,
    slug: "shopping-request",
    title: "Bagaimana cara membuat Daftar Belanja kebutuhan toko ke supplier?",
    aliases: ["buat daftar belanja", "shopping request", "kebutuhan toko supplier", "draft belanja supplier"],
    route: "/suppliers",
    actionLabel: "Buka Daftar Belanja",
    iconKey: "list-plus",
    requiredCapabilities: [{ resource: "supplier", action: "create" }],
    steps: [
      { title: "Buka Supplier", description: "Masuk ke menu Supplier, lalu buka tab Daftar Belanja." },
      { title: "Buat pengajuan", description: "Klik tombol Buat Daftar Belanja di kanan atas tabel." },
      { title: "Pilih supplier", description: "Pilih supplier dari dropdown bila tujuan pembelian sudah diketahui. Supplier bisa dicari dari nama atau kode seperti SP0001." },
      { title: "Tambahkan produk", description: "Gunakan pencarian produk, masukkan requested quantity sesuai unit, dan isi catatan internal bila perlu." },
      { title: "Simpan draft", description: "Klik Simpan Draft Belanja." },
    ],
  }),
  workflow({
    faqNumber: 19,
    slug: "record-expense",
    title: "Bagaimana cara mencatat pengeluaran operasional toko?",
    aliases: ["catat pengeluaran", "tambah pengeluaran", "expense toko", "biaya operasional"],
    route: "/keuangan",
    actionLabel: "Buka Keuangan",
    iconKey: "wallet-cards",
    requiredCapabilities: [{ resource: "expense", action: "create" }],
    steps: [
      { title: "Buka Keuangan", description: "Masuk ke sidebar Keuangan, lalu buka halaman Keuangan." },
      { title: "Tambah pengeluaran", description: "Klik tombol Tambah Pengeluaran untuk membuka form." },
      { title: "Isi nominal dan kategori", description: "Masukkan nominal, kategori, dan catatan pendukung bila diperlukan." },
      { title: "Lampirkan bukti", description: "Jika ada foto nota, unggah ke layanan gambar, salin link, lalu tempel pada URL Lampiran." },
      { title: "Simpan pengeluaran", description: "Periksa pratinjau lampiran dan klik Simpan." },
    ],
  }),
  workflow({
    faqNumber: 20,
    slug: "export-financial-report",
    title: "Bagaimana cara mengekspor Laporan Keuangan ke Excel atau PDF?",
    aliases: ["ekspor laporan keuangan", "export excel pdf", "unduh laporan", "laporan keuangan pdf"],
    route: "/financial-report",
    actionLabel: "Buka Laporan Keuangan",
    iconKey: "file-down",
    requiredCapabilities: [{ resource: "financial-report", action: "read" }],
    steps: [
      { title: "Buka Laporan Keuangan", description: "Masuk ke halaman Laporan Keuangan." },
      { title: "Klik Ekspor", description: "Di kanan atas halaman, klik tombol Ekspor." },
      { title: "Pilih format", description: "Pilih Excel untuk data tabel, termasuk revenue per kategori produk, atau PDF untuk dokumen siap cetak." },
      { title: "Pilih periode", description: "Tentukan Harian, Mingguan, atau Bulanan. Berkas akan mengikuti periode ekspor yang dipilih." },
    ],
  }),
  workflow({
    faqNumber: 21,
    slug: "store-profile",
    title: "Bagaimana cara mengubah informasi profil toko yang muncul di struk?",
    aliases: ["ubah info toko", "profil toko struk", "logo toko", "alamat struk"],
    route: "/settings",
    actionLabel: "Buka Info Toko",
    iconKey: "store",
    requiredCapabilities: [{ resource: "settings", action: "update" }],
    steps: [
      { title: "Buka Pengaturan", description: "Masuk ke Lainnya, lalu Pengaturan." },
      { title: "Pilih Info Toko", description: "Buka tab Info Toko." },
      { title: "Ubah profil", description: "Perbarui logo, nama toko, alamat, dan nomor telepon yang tampil di struk." },
      { title: "Simpan perubahan", description: "Klik Simpan jika semua data sudah benar." },
    ],
  }),
  workflow({
    faqNumber: 22,
    slug: "manage-rbac",
    title: "Bagaimana pemilik toko mengatur hak akses atau izin bagi role?",
    aliases: ["atur hak akses", "mengatur rbac", "izin kasir admin", "permission role"],
    route: "/settings",
    actionLabel: "Buka RBAC",
    iconKey: "shield-check",
    requiredPages: ["/settings"],
    requiredCapabilities: [{ resource: "rbac", action: "update" }],
    steps: [
      { title: "Buka tab RBAC", description: "Masuk ke Pengaturan lalu pilih tab RBAC. Tab ini hanya tersedia untuk OWNER." },
      { title: "Periksa ringkasan", description: "Lihat Ringkasan Role dan Matrix Modul untuk memahami akses tiap role." },
      { title: "Edit izin", description: "Sesuaikan Akses Halaman dan Aksi Resource untuk ADMIN, CASHIER, SALES, atau INVENTORY." },
      { title: "Review perubahan", description: "Klik Review & Simpan untuk melihat ringkasan perubahan." },
      { title: "Konfirmasi sensitif", description: "Jika menyentuh izin sensitif seperti finance, WhatsApp, HPP, RBAC, atau approval, lakukan konfirmasi tambahan sebelum simpan." },
    ],
  }),
  workflow({
    faqNumber: 23,
    slug: "job-order-status",
    title: "Bagaimana cara memperbarui status pengerjaan pesanan cetak?",
    aliases: ["ubah status job order", "kanban produksi", "pesanan cetak", "status produksi"],
    route: "/production",
    actionLabel: "Buka Produksi",
    iconKey: "kanban",
    requiredCapabilities: [{ resource: "production", action: "update" }],
    steps: [
      { title: "Buka Produksi", description: "Masuk ke menu Produksi untuk melihat papan Kanban." },
      { title: "Temukan kartu", description: "Cari kartu pesanan cetak yang ingin diperbarui." },
      { title: "Geser status", description: "Seret kartu ke tahapan Baru, Sedang Diproses, Siap Diambil, atau Selesai sesuai kondisi aktual." },
    ],
  }),
  workflow({
    faqNumber: 24,
    slug: "pickup-notification",
    title: "Bagaimana cara mengirim notifikasi pengambilan barang kepada pelanggan?",
    aliases: ["kirim notifikasi pengambilan", "whatsapp siap diambil", "pesanan siap diambil", "notifikasi pickup"],
    route: "/production",
    actionLabel: "Buka Produksi",
    iconKey: "message-circle",
    requiredCapabilities: [{ resource: "production", action: "update" }, { resource: "whatsapp", action: "create" }],
    steps: [
      { title: "Buka papan Kanban", description: "Masuk ke menu Produksi dan temukan pesanan pada kolom Siap Diambil." },
      { title: "Pilih tombol WhatsApp", description: "Klik tombol WhatsApp pada kartu pesanan tersebut." },
      { title: "Kirim notifikasi", description: "Sistem akan mengirim pesan pengambilan ke nomor pelanggan yang terdaftar sesuai alur aplikasi." },
    ],
  }),
  workflow({
    faqNumber: 25,
    slug: "manage-salespersons",
    title: "Bagaimana cara mengelola daftar anggota Sales?",
    aliases: ["kelola sales", "tambah sales", "anggota sales", "aktifkan sales"],
    route: "/salespersons",
    actionLabel: "Buka Tim Sales",
    iconKey: "users",
    requiredCapabilities: [{ resource: "salesperson", action: "update" }],
    steps: [
      { title: "Buka Tim Sales", description: "Masuk ke menu Tim Sales di sidebar." },
      { title: "Tambah anggota", description: "Klik Tambah Sales, isi nama anggota baru, lalu simpan." },
      { title: "Ubah anggota", description: "Gunakan tombol edit untuk mengubah nama sales." },
      { title: "Atur status aktif", description: "Gunakan toggle cepat untuk mengaktifkan atau menonaktifkan anggota. Hanya sales aktif yang muncul di POS." },
    ],
  }),
  workflow({
    faqNumber: 26,
    slug: "salesperson-history",
    title: "Bagaimana cara melihat riwayat transaksi yang ditangani Sales tertentu?",
    aliases: ["riwayat transaksi sales", "transaksi sales tertentu", "kontribusi sales", "detail sales"],
    route: "/salespersons",
    actionLabel: "Buka Tim Sales",
    iconKey: "history",
    requiredCapabilities: [{ resource: "salesperson", action: "read" }],
    steps: [
      { title: "Buka Tim Sales", description: "Masuk ke menu Tim Sales." },
      { title: "Pilih sales", description: "Klik baris atau kartu nama sales yang ingin diperiksa." },
      { title: "Baca rincian", description: "Panel profil akan menampilkan rincian sales dan maksimal 20 transaksi terbaru yang ditangani." },
    ],
  }),
  workflow({
    faqNumber: 27,
    slug: "inventory-day-session",
    title: "Bagaimana cara melakukan Check In dan Check Out bagi staf gudang?",
    aliases: ["check in inventaris", "check out inventaris", "day session gudang", "morning check"],
    route: "/inventory",
    actionLabel: "Buka Inventaris",
    iconKey: "calendar-check",
    requiredCapabilities: [{ resource: "inventory", action: "update" }],
    steps: [
      { title: "Buka Inventaris", description: "Masuk ke halaman Inventaris pada awal hari kerja." },
      { title: "Selesaikan Check In", description: "Isi Morning Check: risiko stok, hitung bahan produksi utama, dan checklist area kerja serta keselamatan." },
      { title: "Kerjakan tugas harian", description: "Setelah Check In selesai, tab Tugas terbuka untuk pekerjaan harian inventaris." },
      { title: "Mulai Check Out", description: "Di akhir hari, buka ringkasan sesi dan klik Check Out." },
      { title: "Penuhi syarat penutupan", description: "Pastikan tugas harian selesai. Pada Sabtu, tempel link prnt.sc Proof Kebersihan sebelum menutup sesi." },
    ],
  }),
  workflow({
    faqNumber: 28,
    slug: "delivery-order-marking",
    title: "Bagaimana cara melakukan marking pada Surat Jalan?",
    aliases: ["marking surat jalan", "tandai surat jalan", "delivery order marking", "sj unmarked"],
    route: "/inventory",
    actionLabel: "Buka Surat Jalan Inventaris",
    iconKey: "clipboard-signature",
    requiredCapabilities: [{ resource: "surat_jalan", action: "update" }],
    steps: [
      { title: "Buka antrean Surat Jalan", description: "Di Inventaris, buka tab Ringkasan atau Transaksi lalu Surat Jalan." },
      { title: "Cari status UNMARKED", description: "Temukan Surat Jalan yang belum ditandai di antrean gudang." },
      { title: "Klik Marking", description: "Gunakan tombol Marking pada baris Surat Jalan tersebut." },
      { title: "Pilih status penanganan", description: "Pilih status seperti Selesai, Belum Dikirim, Perlu Tanda Tangan, Perlu Follow Up, Ditunda, atau Tidak Relevan." },
      { title: "Simpan catatan", description: "Isi catatan untuk status pengecualian, lalu klik Simpan. Check Out terblokir jika masih ada Surat Jalan UNMARKED." },
    ],
  }),
  workflow({
    faqNumber: 29,
    slug: "approve-stock-logs",
    title: "Bagaimana cara menyetujui atau menolak pengajuan mutasi/Log Stok?",
    aliases: [
      "approval stock logs",
      "menyetujui stock logs",
      "tolak log stok",
      "persetujuan stok masuk",
      "konfirmasi mutasi stok",
    ],
    route: "/inventory",
    actionLabel: "Buka Inventaris",
    iconKey: "shield-check",
    requiredCapabilities: [{ resource: "inventory.approve", action: "update" }],
    steps: [
      { title: "Buka Inventaris", description: "Buka menu samping (sidebar) sebelah kiri layar Anda, lalu klik menu Inventaris." },
      { title: "Pilih sub-tab Log Stok", description: "Klik tab Riwayat di navigasi atas, kemudian pilih sub-tab Log Stok. Atau klik langsung badge notifikasi oranye di sidebar jika ada." },
      { title: "Beri keputusan persetujuan", description: "Cari pengajuan yang berstatus Pending (kuning) di tabel. Klik Setuju (hijau) untuk mengesahkan stok, atau Tolak (merah) untuk membatalkannya." },
      { title: "Tulis alasan jika ditolak", description: "Jika Anda memilih untuk menolak pengajuan, ketik alasan penolakan pada kolom pop-up yang muncul, lalu konfirmasi penolakan." },
    ],
  }),
  workflow({
    faqNumber: 30,
    slug: "inventory-workflow",
    title: "Bagaimana alur kerja harian staf gudang (Inventory)?",
    aliases: [
      "alur kerja inventaris",
      "alur kerja staf gudang",
      "alur kerja inventory",
      "harian gudang",
      "tugas harian gudang",
    ],
    route: "/inventory",
    actionLabel: "Buka Inventaris",
    iconKey: "warehouse",
    requiredCapabilities: [
      { resource: "inventory", action: "update" },
      { resource: "inventory.out_log.verify", action: "update" },
    ],
    steps: [
      { title: "Verifikasi Log OUT Belum Diverifikasi", description: "Setelah Check In, buka tab Tugas lalu Tugas Harian dan klik Log OUT Belum Diverifikasi. Verifikasi ini mengecek kebenaran catatan Log OUT, bukan matching stok fisik." },
      { title: "Beri keputusan Log OUT", description: "Klik Setujui jika catatan sudah benar. Klik Perlu Koreksi jika produk, qty, alasan, atau catatan perlu diperbaiki; baris berubah warna dan badge menjadi Perlu Koreksi." },
      { title: "Ajukan koreksi bila perlu", description: "Pada baris Perlu Koreksi, gunakan tombol Koreksi untuk mengisi data yang benar. Koreksi menunggu approval maker-checker sebelum baris siap dicek ulang dan disetujui." },
      { title: "Matching Stok Harian", description: "Pukul 15:00-20:00 WIB, buka Matching Stok Harian. Klik input Stok Gudang per baris; indikator hijau berarti sesuai, merah berarti selisih, dan kuning berarti belum valid. Baris selisih wajib memakai catatan sebelum Submit Matching." },
      { title: "Input Penerimaan Barang", description: "Saat barang dari supplier datang, buka tab Transaksi lalu Penerimaan Barang. Pilih invoice daftar belanja, cek badge Sudah dibuat atau Sudah lengkap, isi kuantitas fisik, lalu Ajukan ke Owner." },
      { title: "Catat Barang Pecah/Rusak", description: "Jika ada barang rusak, pilih menu Input / Transaksi lalu Laporkan Barang Rusak untuk mencatat penyesuaian stok." },
    ],
  }),
  workflow({
    faqNumber: 31,
    slug: "cashier-workflow",
    title: "Bagaimana alur kerja harian staf Kasir?",
    aliases: [
      "alur kerja kasir",
      "tugas harian kasir",
      "operasional kasir",
      "harian kasir",
    ],
    route: "/pos",
    actionLabel: "Buka Kasir",
    iconKey: "shopping-cart",
    requiredCapabilities: [{ resource: "shift", action: "update" }, { resource: "transaction", action: "create" }],
    steps: [
      { title: "Mulai Shift Kasir", description: "Sebelum bertransaksi, buka menu Shift Kasir di kategori Lainnya, isi nominal modal kas awal di laci fisik, lalu klik Mulai Shift." },
      { title: "Layani Transaksi POS", description: "Buka menu Kasir (POS) di sidebar, pilih produk pesanan pelanggan, klik Bayar, input nominal uang, lalu cetak struk pembayaran." },
      { title: "Catat Pengeluaran Laci", description: "Jika ada pengeluaran kas darurat, klik ikon dompet Pengeluaran di bagian atas layar POS, isi nominal dan alasan, lalu Simpan." },
      { title: "Proses Transaksi Pending", description: "Cek transaksi bertanda pending (biru) di Riwayat. Klik Setuju/Tolak di kolom aksi, tentukan pembayaran, lalu konfirmasi." },
      { title: "Tutup Shift Kasir", description: "Di akhir hari kerja, klik profil Anda di pojok kanan atas, pilih Tutup Shift, hitung uang fisik laci, lalu klik Konfirmasi Akhiri Shift." },
    ],
  }),
  workflow({
    faqNumber: 32,
    slug: "sales-workflow",
    title: "Bagaimana alur kerja harian staf Sales?",
    aliases: [
      "alur kerja sales",
      "tugas harian sales",
      "operasional sales",
      "harian sales",
    ],
    route: "/pos",
    actionLabel: "Buka Kasir",
    iconKey: "users",
    requiredCapabilities: [{ resource: "transaction", action: "create" }],
    steps: [
      { title: "Melayani Pelanggan", description: "Sambut pelanggan dengan ramah dan bantu cari produk atau tanyakan kebutuhan barang yang mereka cari." },
      { title: "Pilih Produk di POS", description: "Buka menu Kasir (POS) di sidebar kiri, masukkan produk-produk pesanan pelanggan ke dalam keranjang belanja." },
      { title: "Kirim Permintaan Pembayaran", description: "Kirimkan detail tagihan pesanan pembeli melalui sistem untuk proses pembayaran." },
      { title: "Cetak Invoice Tagihan", description: "Cetak 2 rangkap invoice tagihan pesanan dari sistem sebagai tanda bukti pesanan resmi." },
      { title: "Serahkan Nota ke Pelanggan", description: "Berikan satu rangkap invoice kepada pelanggan sebagai rincian belanja mereka." },
      { title: "Serahkan Uang ke Kasir", description: "Menyerahkan rangkap invoice kedua beserta uang pembayaran dari pelanggan kepada Kasir untuk diproses (Checkout)." },
    ],
  }),
  workflow({
    faqNumber: 33,
    slug: "change-individual-stock",
    title: "Bagaimana cara mengubah stok individual produk lewat tombol \"Ubah Produk\"?",
    aliases: [
      "ubah stok individual",
      "ganti stok produk",
      "edit stok individual",
      "ubah produk untuk stok",
      "stok saat ini produk"
    ],
    route: "/products",
    actionLabel: "Buka Produk",
    iconKey: "package",
    requiredCapabilities: [{ resource: "product", action: "update" }],
    steps: [
      { title: "Buka menu katalog", description: "Masuk ke sidebar Katalog, lalu buka halaman Produk." },
      { title: "Cari produk", description: "Temukan produk yang ingin disesuaikan kuantitas stoknya pada daftar tabel produk." },
      { title: "Klik tombol Ubah Produk", description: "Klik ikon pensil (Ubah Produk) di kolom paling kanan pada baris produk yang dipilih." },
      { title: "Ubah data stok", description: "Cari kolom input 'Stok Saat Ini' pada formulir modal edit produk, lalu ketik jumlah stok yang baru." },
      { title: "Simpan produk", description: "Periksa kembali data Anda, lalu klik tombol Simpan Produk untuk menyimpan stok baru ke sistem." }
    ],
  }),
  workflow({
    faqNumber: 34,
    slug: "update-stok-massal-product-first",
    title: "Bagaimana cara memakai Update Stok untuk satu produk dan banyak produk?",
    aliases: [
      "update stok",
      "update stok satu produk",
      "update stok massal",
      "ubah banyak stok produk",
      "stok bersama",
      "stok produk ini",
      "bulk grup stok",
      "update stok grup dari produk"
    ],
    route: "/inventory",
    actionLabel: "Buka Inventaris",
    iconKey: "warehouse",
    requiredCapabilities: [{ resource: "inventory", action: "update" }],
    steps: [
      { title: "Buka Update Stok", description: "Masuk ke halaman Inventaris, lalu klik tombol Update Stok di sebelah Input / Transaksi." },
      { title: "Pilih jalur", description: "Pilih Satu Produk (Single) untuk update satu produk dengan tampilan ringkas, atau pilih Banyak Produk (Bulk) untuk membuka workflow Update Stok Massal yang sudah ada." },
      { title: "Cari produk", description: "Di Satu Produk, cari dan pilih satu produk. Di Banyak Produk (Bulk), gunakan pencarian produk untuk menambahkan setiap produk atau varian yang stoknya mau diubah. Thumbnail/foto produk tampil di hasil pencarian dan kartu pilihan agar barang mudah dicek." },
      { title: "Atur aksi dan jumlah", description: "Pilih Tambah stok, Kurangi stok, atau Set stok akhir. Untuk Bulk, setiap produk punya aksi, input stok, catatan, dan mode sendiri." },
      { title: "Pilih mode stok", description: "Pilih Stok Bersama untuk menghitung dampak ke stok grup dan varian lain. Pilih Stok Produk Ini jika hanya produk itu yang dibuatkan log stok dan stok grup tidak diubah." },
      { title: "Cek preview dan konflik", description: "Cek preview dengan foto produk/varian, lalu pastikan tidak ada produk duplikat. Jika dua varian dari grup yang sama sama-sama memakai Stok Bersama, ikuti pesan Pilih satu produk saja per grup stok untuk mode Stok Bersama." },
      { title: "Ajukan approval", description: "Klik submit untuk membuat pengajuan. Stok Bersama tampil sebagai bundle di Stock Log, sedangkan Stok Produk Ini menjadi log terpisah sampai approval selesai." },
    ],
  }),
];

export function getWorkflowPayload(workflow: AssistantWorkflowDefinition): AssistantWorkflowPayload {
  return {
    id: workflow.id,
    title: workflow.title,
    route: workflow.route,
    actionLabel: workflow.actionLabel,
    sourceRef: workflow.sourceRef,
    steps: workflow.steps.map((step) => ({
      id: step.id,
      title: step.title,
      description: step.description,
      route: step.route,
      actionLabel: step.actionLabel,
      iconKey: step.iconKey,
    })),
  };
}
