import type { ResourceAction, Role } from "@/features/rbac/helpers/rbac-core";
import type { AssistantWorkflowPayload, AssistantWorkflowStepPayload } from "../types/assistant";

export type AssistantWorkflowRequirement = {
  resource: string;
  action: ResourceAction;
};

export type AssistantWorkflowDefinition = AssistantWorkflowPayload & {
  faqNumber: number;
  aliases: string[];
  requiredPages: string[];
  requiredCapabilities: AssistantWorkflowRequirement[];
  allowedRoles?: Role[];
  iconKey: string;
  steps: Required<AssistantWorkflowStepPayload>[];
};

type WorkflowInput = {
  faqNumber: number;
  slug: string;
  title: string;
  aliases: string[];
  route: string;
  actionLabel: string;
  iconKey: string;
  allowedRoles?: Role[];
  requiredPages?: string[];
  requiredCapabilities: AssistantWorkflowRequirement[];
  steps: Array<{ title: string; description: string }>;
};

function sourceAnchor(title: string) {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-");
}

function workflow(input: WorkflowInput): AssistantWorkflowDefinition {
  const id = `faq-q${String(input.faqNumber).padStart(2, "0")}-${input.slug}`;
  return {
    id,
    faqNumber: input.faqNumber,
    title: input.title,
    aliases: input.aliases,
    requiredPages: input.requiredPages ?? [input.route],
    requiredCapabilities: input.requiredCapabilities,
    allowedRoles: input.allowedRoles,
    route: input.route,
    actionLabel: input.actionLabel,
    sourceRef: `docs/help/faq.md#q${input.faqNumber}-${sourceAnchor(input.title)}`,
    iconKey: input.iconKey,
    steps: input.steps.map((step, index) => ({
      id: `${id}-step-${index + 1}`,
      title: step.title,
      description: step.description,
      route: input.route,
      actionLabel: input.actionLabel,
      iconKey: input.iconKey,
    })),
  };
}

export const FAQ_WORKFLOWS: AssistantWorkflowDefinition[] = [
  workflow({
    faqNumber: 1,
    slug: "add-product",
    title: "Bagaimana cara menambahkan produk baru ke katalog toko?",
    aliases: ["tambah produk", "menambahkan produk baru", "buat produk baru", "input produk katalog", "harga agen produk", "merek produk", "brand produk"],
    route: "/products",
    actionLabel: "Buka Produk",
    iconKey: "package",
    requiredCapabilities: [{ resource: "product", action: "create" }],
    steps: [
      { title: "Buka katalog produk", description: "Masuk ke sidebar Katalog, lalu buka halaman Produk." },
      { title: "Mulai tambah produk", description: "Klik tombol Tambah Produk di kanan atas halaman, atau minta Pak Teladan membuka modal Tambah Produk." },
      { title: "Isi data utama", description: "Lengkapi nama produk, SKU unik, kategori, merek bila ada, harga jual, Harga Agen atau Harga Dinas bila perlu, stok awal, satuan, dan batas minimum stok. Jika merek belum tersedia, tambah merek baru dari form." },
      { title: "Tambahkan varian bila perlu", description: "Jika barang punya unit pecahan, tambahkan varian unit terkecil beserta SKU, barcode, dan harga jualnya." },
      { title: "Simpan produk", description: "Periksa ulang isian, lalu klik Simpan. Pak Teladan dapat membuka halaman dan modal, tetapi tidak mengisi atau menyimpan form otomatis." },
    ],
  }),
  workflow({
    faqNumber: 2,
    slug: "change-product-price",
    title: "Bagaimana cara mengubah harga jual produk agar tercatat di riwayat?",
    aliases: ["ubah harga produk", "ganti harga jual", "riwayat harga", "ubah harga jual produk", "ubah harga agen", "ubah harga dinas"],
    route: "/products",
    actionLabel: "Buka Produk",
    iconKey: "dollar-sign",
    requiredCapabilities: [{ resource: "product", action: "update" }],
    steps: [
      { title: "Buka daftar produk", description: "Masuk ke halaman Produk dan temukan produk yang harganya akan diubah." },
      { title: "Pilih Ubah Harga", description: "Gunakan tombol aksi Ubah Harga pada baris produk untuk perubahan cepat yang tercatat di Riwayat Harga." },
      { title: "Isi harga baru", description: "Masukkan nominal harga jual, HPP, Harga Dinas, atau Harga Agen pada modal yang muncul, lalu simpan jika sudah benar." },
      { title: "Gunakan Edit untuk detail penuh", description: "Jika perlu mengubah data produk lain, buka aksi Edit pada baris produk." },
    ],
  }),
  workflow({
    faqNumber: 3,
    slug: "customer-special-pricing",
    title: "Bagaimana cara mengatur harga khusus/diskon bagi grup pelanggan?",
    aliases: ["harga khusus pelanggan", "diskon agen", "harga agen", "harga dinas", "harga pelanggan industri", "harga khusus semua pelanggan", "diskon unit", "diskon merek", "brand harga khusus"],
    route: "/products",
    actionLabel: "Buka Harga Khusus",
    iconKey: "badge-percent",
    requiredCapabilities: [{ resource: "product", action: "update" }],
    steps: [
      { title: "Buka Harga Khusus", description: "Masuk ke halaman Produk, lalu buka bagian Harga Khusus. Fitur ini biasanya dibatasi untuk OWNER." },
      { title: "Pilih tipe pelanggan", description: "Tentukan Semua pelanggan atau grup tertentu seperti UMUM, AGEN, INDUSTRI, atau PEMERINTAH. Harga Agen dan Harga Dinas di produk tetap dipakai lebih dulu jika tersedia." },
      { title: "Pilih kategori, unit, dan merek", description: "Pilih kategori produk. Isi Unit jika aturan hanya untuk unit tertentu, atau kosongkan untuk semua unit. Pilih merek tertentu, Semua merek, atau tambah merek baru dari form." },
      { title: "Pilih mode dan nilai", description: "Tentukan Diskon Persen atau Diskon Rupiah, lalu isi nilai diskon." },
      { title: "Simpan aturan", description: "Klik Simpan. Aturan akan dipakai di kasir saat kategori, unit, merek, dan tipe pelanggan cocok." },
    ],
  }),
  workflow({
    faqNumber: 4,
    slug: "bulk-product-import",
    title: "Bagaimana cara mengimpor produk, stok, atau kode supplier secara massal?",
    aliases: ["import produk excel", "import stok excel", "bulk product import", "unggah produk massal", "import harga agen", "import kode supplier produk"],
    route: "/products",
    actionLabel: "Buka Import Produk",
    iconKey: "file-spreadsheet",
    requiredCapabilities: [{ resource: "product", action: "create" }, { resource: "inventory", action: "update" }],
    steps: [
      { title: "Buka Fitur Import", description: "Di halaman Pusat Produk, klik tombol dropdown Import di kanan atas." },
      { title: "Pilih tipe impor", description: "Pilih Impor Produk Massal untuk katalog, Impor Stok Massal untuk kuantitas stok, atau Impor Kode Supplier Massal untuk memperbarui relasi supplier berdasarkan SKU." },
      { title: "Unggah Excel", description: "Pilih file .xlsx dari perangkat, lalu lakukan pemetaan kolom jika nama kolom berbeda. Kolom opsional termasuk Harga Agen, Harga Dinas, dan Kode Supplier." },
      { title: "Periksa pratinjau", description: "Cek Harga Agen, Harga Dinas, kode supplier, dan keputusan setiap baris sebelum menyelesaikan impor. Untuk impor kode supplier, pastikan semua SKU dan kode supplier berstatus Siap; relasi supplier lama akan diganti sesuai berkas. Impor produk berjalan di antrean latar belakang; pantau progres, lalu gunakan Coba Lagi jika antrean belum berhasil dimulai." },
    ],
  }),
  workflow({
    faqNumber: 5,
    slug: "stock-group",
    title: "Bagaimana cara mengatur Grup Stok (Stock Group)?",
    aliases: ["atur grup stok", "stock group", "gabungkan stok produk", "bulk stock group"],
    route: "/products",
    actionLabel: "Buka Grup Stok",
    iconKey: "boxes",
    requiredCapabilities: [{ resource: "product", action: "update" }],
    steps: [
      { title: "Buka aktivitas grup", description: "Masuk ke tab Aktivitas Grup di halaman Pusat Produk." },
      { title: "Mulai pengaturan", description: "Klik Atur Grup Stok atau buka Grup Stok Massal dari menu import." },
      { title: "Pilih produk utama", description: "Tentukan produk utama dan tambahkan produk anggota yang berbagi stok fisik." },
      { title: "Simpan grup", description: "Simpan pengaturan agar mutasi dan pemakaian grup stok tercatat di aktivitas." },
    ],
  }),
  workflow({
    faqNumber: 6,
    slug: "pos-sale",
    title: "Bagaimana alur memproses transaksi penjualan langsung di kasir?",
    aliases: ["proses transaksi kasir", "jualan di POS", "bayar di kasir", "alur pos", "edit cepat harga pos", "ubah produk dari keranjang"],
    route: "/pos",
    actionLabel: "Buka Kasir",
    iconKey: "shopping-cart",
    requiredCapabilities: [{ resource: "transaction", action: "create" }],
    steps: [
      { title: "Pastikan shift aktif", description: "Buka shift kasir terlebih dahulu sebelum memproses transaksi." },
      { title: "Pilih item", description: "Cari produk atau layanan, pilih varian jika ada, lalu masukkan ke keranjang." },
      { title: "Edit cepat bila diperlukan", description: "Jika memiliki permission edit produk, aktifkan Edit Cepat di header keranjang. Ikon produk mengubah Nama/Kategori/Merek seluruh varian; ikon harga mengubah harga master varian atau Harga Khusus yang hanya berlaku untuk transaksi ini." },
      { title: "Periksa keranjang", description: "Atur kuantitas atau hapus item yang tidak sesuai, lalu klik Bayar." },
      { title: "Isi pembayaran", description: "Pilih pelanggan, sales bila perlu, metode pembayaran, status Lunas atau DP, dan tipe transaksi. Owner/Admin dapat mengisi Tanggal Invoice dan Jam Invoice opsional jika invoice harus memakai tanggal bisnis tertentu." },
      { title: "Konfirmasi dan cetak", description: "Klik Konfirmasi Bayar atau Bayar DP, lalu cetak struk bila diperlukan." },
    ],
  }),
  workflow({
    faqNumber: 7,
    slug: "approve-pending-transaction",
    title: "Bagaimana cara menyetujui transaksi Pending atau mengatur auto approve per role?",
    aliases: ["setujui transaksi pending", "approval transaksi sales", "transaksi pending", "approve transaksi", "auto approve transaksi", "rbac auto approve"],
    route: "/history",
    actionLabel: "Buka Riwayat",
    iconKey: "clipboard-check",
    requiredCapabilities: [{ resource: "transaction.approve", action: "update" }],
    steps: [
      { title: "Pilih alur approval", description: "Tanpa izin transaction.auto_approve.create, transaksi role masuk Pending. Owner dapat mengaktifkan Auto Approve Transaksi pada Pengaturan > RBAC agar checkout role tersebut langsung final." },
      { title: "Buka Riwayat", description: "Untuk transaksi yang tetap Pending, masuk ke Riwayat Transaksi dan gunakan filter Pending." },
      { title: "Pilih aksi", description: "Klik Setujui atau Tolak pada baris transaksi, atau gunakan menu tiga titik." },
      { title: "Isi modal persetujuan", description: "Pilih Bayar Instan atau Bayar Nanti, lalu lengkapi metode dan nominal pembayaran. Owner/Admin dapat mengubah Tanggal Invoice atau Jam Invoice final bila perlu." },
      { title: "Finalisasi keputusan", description: "Klik Setujui untuk memotong stok dan memfinalisasi, atau Tolak untuk membatalkan transaksi pending. Jika tanggal/nomor invoice final berubah, cetak ulang invoice final." },
    ],
  }),
  workflow({
    faqNumber: 8,
    slug: "create-delivery-order",
    title: "Bagaimana cara membuat Surat Jalan Pengiriman barang ke pelanggan?",
    aliases: ["buat surat jalan", "cetak surat jalan", "delivery order", "pengiriman barang pelanggan"],
    route: "/history",
    actionLabel: "Buka Riwayat",
    iconKey: "truck",
    requiredCapabilities: [{ resource: "surat_jalan", action: "create" }],
    steps: [
      { title: "Cari transaksi", description: "Temukan transaksi Lunas atau DP yang memiliki produk fisik di halaman Riwayat." },
      { title: "Buka aksi Surat Jalan", description: "Klik menu tiga titik pada baris transaksi, lalu pilih Cetak Surat Jalan." },
      { title: "Buat dokumen", description: "Klik Buat Surat Jalan atau Buat Surat Jalan Baru jika sudah ada pengiriman sebelumnya." },
      { title: "Isi detail pengiriman", description: "Masukkan jumlah barang, kurir, pengemudi, pelat kendaraan, penerima, dan catatan bila perlu." },
      { title: "Simpan dokumen", description: "Proses Surat Jalan agar tersimpan dan siap dicetak sebagai bukti pengiriman." },
    ],
  }),
  workflow({
    faqNumber: 9,
    slug: "print-invoice",
    title: "Bagaimana cara mencetak invoice atau struk transaksi?",
    aliases: ["cetak invoice", "cetak struk", "print invoice", "struk transaksi"],
    route: "/history",
    actionLabel: "Buka Riwayat",
    iconKey: "printer",
    requiredCapabilities: [{ resource: "transaction", action: "read" }],
    steps: [
      { title: "Pilih jalur cetak", description: "Cetak dari POS setelah pembayaran selesai, atau dari Riwayat untuk transaksi lama." },
      { title: "Buka transaksi", description: "Di Riwayat, cari dan klik baris transaksi yang ingin dicetak." },
      { title: "Gunakan tombol cetak", description: "Pada panel detail, klik ikon printer atau tombol Cetak Invoice/Struk." },
    ],
  }),
  workflow({
    faqNumber: 10,
    slug: "custom-invoice-date",
    title: "Bagaimana cara mengubah tanggal invoice transaksi?",
    aliases: ["ubah tanggal invoice", "ganti tanggal invoice", "custom invoice date", "tanggal faktur", "ubah nomor invoice"],
    route: "/history",
    actionLabel: "Buka Riwayat",
    iconKey: "calendar",
    allowedRoles: ["OWNER", "ADMIN"],
    requiredCapabilities: [{ resource: "transaction", action: "update" }],
    steps: [
      { title: "Buka Riwayat", description: "Masuk ke Riwayat Transaksi. Tanggal utama memakai Tanggal Invoice, sedangkan label Dibuat menunjukkan waktu sistem membuat record." },
      { title: "Pilih transaksi", description: "Cari transaksi yang ingin diperbaiki tanggalnya, lalu buka menu tiga titik pada baris tersebut." },
      { title: "Klik Ubah Tanggal Invoice", description: "Pilih menu Ubah Tanggal Invoice. Fitur ini hanya tersedia untuk Owner/Admin." },
      { title: "Isi perubahan", description: "Pilih tanggal baru, isi jam hanya jika ingin mengganti jam invoice, lalu tulis alasan perubahan. Jika jam kosong, jam invoice sebelumnya dipertahankan." },
      { title: "Simpan dan cetak ulang", description: "Sistem menyesuaikan nomor invoice/draft, mencatat audit trail, dan invoice final harus dicetak ulang setelah perubahan." },
    ],
  }),
  workflow({
    faqNumber: 11,
    slug: "upload-receipt-proof",
    title: "Bagaimana cara mengunggah foto nota atau bukti transaksi?",
    aliases: ["unggah bukti transaksi", "upload nota", "foto struk", "url lampiran"],
    route: "/history",
    actionLabel: "Buka Riwayat",
    iconKey: "image",
    requiredCapabilities: [{ resource: "transaction", action: "update" }],
    steps: [
      { title: "Pilih dan putar gambar bukti", description: "Di modal bukti transaksi, klik Pilih gambar bukti. Gunakan Putar kiri atau Putar kanan sampai orientasi benar, lalu klik Unggah foto." },
      { title: "Tunggu unggahan R2", description: "Sistem mengecilkan dimensi, menghapus metadata, dan memastikan gambar dikompresi sebelum mengunggahnya ke R2 lalu menampilkan pratinjau." },
      { title: "Gunakan fallback bila perlu", description: "Jika penyimpanan R2 gagal, input prnt.sc muncul. Unggah gambar ke prnt.sc dan tempel tautannya sebagai fallback." },
      { title: "Simpan atau hapus lampiran", description: "Periksa pratinjau, tambahkan gambar lain bila perlu, lalu klik Simpan. Tombol Hapus foto tersedia bagi OWNER atau role yang diberi izin proof_upload:delete; R2 dihapus permanen dan prnt.sc hanya dikosongkan tautannya." },
    ],
  }),
  workflow({
    faqNumber: 12,
    slug: "cashier-shift",
    title: "Bagaimana cara memulai dan mengakhiri shift kerja kasir?",
    aliases: ["buka shift", "tutup shift", "mulai shift kasir", "akhiri shift kasir"],
    route: "/shift",
    actionLabel: "Buka Shift Kasir",
    iconKey: "wallet",
    requiredCapabilities: [{ resource: "shift", action: "create" }, { resource: "shift", action: "update" }],
    steps: [
      { title: "Buka Shift Kasir", description: "Masuk ke menu Shift Kasir saat baru mulai kerja." },
      { title: "Isi kas awal", description: "Ketik nominal modal uang tunai awal yang ada di laci kasir." },
      { title: "Mulai shift", description: "Klik Mulai Shift agar transaksi kasir bisa berjalan." },
      { title: "Tutup shift", description: "Di akhir kerja, hitung uang fisik, isi nominal tutup laci dan catatan bila perlu." },
      { title: "Konfirmasi akhir", description: "Klik Konfirmasi Akhiri Shift untuk membandingkan kas fisik dengan catatan sistem." },
    ],
  }),
  workflow({
    faqNumber: 13,
    slug: "edit-closed-shift",
    title: "Bagaimana cara mengoreksi laporan shift kasir yang sudah ditutup?",
    aliases: ["ubah laporan shift", "koreksi shift", "edit shift tertutup", "saldo akhir shift salah"],
    route: "/shift",
    actionLabel: "Buka Shift Kasir",
    iconKey: "pencil",
    requiredCapabilities: [{ resource: "shift", action: "update" }],
    steps: [
      { title: "Buka Riwayat Shift", description: "Masuk ke tab Riwayat di halaman Shift Kasir." },
      { title: "Cari shift", description: "Temukan baris shift yang perlu dikoreksi." },
      { title: "Edit data", description: "Klik ikon pensil, sesuaikan saldo akhir atau catatan, lalu simpan." },
    ],
  }),
  workflow({
    faqNumber: 14,
    slug: "add-customer",
    title: "Bagaimana cara mendaftarkan pelanggan baru ke sistem?",
    aliases: ["tambah pelanggan", "daftar pelanggan baru", "input customer", "buat customer baru"],
    route: "/customers",
    actionLabel: "Buka Pelanggan",
    iconKey: "user-plus",
    requiredCapabilities: [{ resource: "customer", action: "create" }],
    steps: [
      { title: "Buka Pelanggan", description: "Masuk ke menu Pelanggan, lalu buka halaman Pelanggan." },
      { title: "Klik Tambah Pelanggan", description: "Gunakan tombol Tambah Pelanggan di kanan atas, atau Import Excel untuk data massal." },
      { title: "Isi profil", description: "Lengkapi nama wajib, tipe pelanggan, nomor HP, email, perusahaan, alamat, dan catatan." },
      { title: "Simpan pelanggan", description: "Periksa data, lalu klik Simpan." },
    ],
  }),
  workflow({
    faqNumber: 15,
    slug: "customer-debt-payment",
    title: "Bagaimana cara mencatat pembayaran cicilan atau pelunasan piutang pelanggan?",
    aliases: ["bayar piutang", "pelunasan piutang", "cicilan pelanggan", "bayar hutang pelanggan"],
    route: "/customers",
    actionLabel: "Buka Piutang Pelanggan",
    iconKey: "receipt",
    requiredCapabilities: [{ resource: "customer", action: "update" }],
    steps: [
      { title: "Buka tab Piutang", description: "Di halaman Pelanggan, pilih tab Piutang." },
      { title: "Pilih invoice", description: "Cari invoice yang ingin dilunasi atau dicicil, lalu klik Bayar Piutang." },
      { title: "Isi pembayaran", description: "Pilih satu atau beberapa metode pembayaran dan isi nominal untuk masing-masing metode." },
      { title: "Proses pembayaran", description: "Tambahkan catatan bila perlu, lalu klik Proses Pembayaran." },
      { title: "Alternatif dari Riwayat", description: "Untuk transaksi DP, buka detail transaksi di Riwayat dan gunakan tombol Bayar Cicilan." },
    ],
  }),
  workflow({
    faqNumber: 16,
    slug: "damaged-stock-report",
    title: "Bagaimana cara melaporkan barang rusak, hilang, atau menyusut di gudang?",
    aliases: ["lapor barang rusak", "barang hilang", "stok menyusut", "laporan kerusakan gudang"],
    route: "/inventory",
    actionLabel: "Buka Inventaris",
    iconKey: "triangle-alert",
    requiredCapabilities: [{ resource: "inventory", action: "update" }],
    steps: [
      { title: "Buka Inventaris", description: "Masuk ke halaman Inventaris dan klik menu Input / Transaksi." },
      { title: "Pilih laporan rusak", description: "Pilih opsi Laporkan Barang Rusak." },
      { title: "Isi detail", description: "Pilih produk, masukkan jumlah stok yang rusak, hilang, atau menyusut, lalu tulis alasan." },
      { title: "Pilih gambar bukti", description: "Unggah foto barang rusak ke penyimpanan R2. Jika R2 gagal, gunakan input prnt.sc yang muncul sebagai fallback." },
      { title: "Submit laporan", description: "Klik Submit. Laporan akan tersimpan atau masuk proses persetujuan sesuai aturan gudang." },
    ],
  }),
  workflow({
    faqNumber: 17,
    slug: "weekly-proof-task",
    title: "Bagaimana cara menyelesaikan tugas operasional mingguan?",
    aliases: ["proof kebersihan", "tugas mingguan", "unggah kebersihan gudang", "weekly proof"],
    route: "/inventory",
    actionLabel: "Buka Tugas Inventaris",
    iconKey: "clipboard-list",
    requiredCapabilities: [{ resource: "inventory", action: "update" }],
    steps: [
      { title: "Buka tab Tugas", description: "Di halaman Inventaris, buka tab Tugas. Check In mungkin diperlukan lebih dulu." },
      { title: "Pilih tugas mingguan", description: "Temukan tugas seperti Proof Kebersihan Gudang." },
      { title: "Pilih gambar bukti", description: "Klik tugas atau tombol aksi, lalu unggah foto ke R2. Jika R2 gagal, gunakan input prnt.sc yang muncul sebagai fallback." },
      { title: "Submit tugas", description: "Cek pratinjau gambar, lalu klik Submit Proof agar tugas tercatat selesai." },
    ],
  }),
  workflow({
    faqNumber: 18,
    slug: "inbound-receipt",
    title: "Bagaimana cara mengajukan Penerimaan Barang dari supplier?",
    aliases: ["penerimaan barang", "inbound receipt", "barang masuk supplier", "ajukan penerimaan"],
    route: "/inventory",
    actionLabel: "Buka Penerimaan Barang",
    iconKey: "package-plus",
    requiredCapabilities: [{ resource: "inventory", action: "update" }],
    steps: [
      { title: "Buka Penerimaan Barang", description: "Di halaman Inventaris, buka tab Transaksi lalu pilih Penerimaan Barang." },
      { title: "Pilih invoice daftar belanja", description: "Klik Terima barang, lalu pilih invoice dari daftar belanja. Opsi berwarna membantu membedakan invoice yang belum dipakai, punya badge Sudah dibuat, atau sudah lengkap diterima." },
      { title: "Isi kuantitas fisik", description: "Periksa item invoice, isi jumlah barang yang benar-benar datang, dan tambahkan catatan jika ada selisih atau kondisi khusus." },
      { title: "Ajukan ke Owner", description: "Klik Ajukan ke Owner. Pengajuan belum menambah stok sampai ada keputusan dari role yang memiliki izin RBAC granular inventory.inbound_receipt.approve, inventory.inbound_receipt.reject, atau inventory.inbound_receipt.revise." },
      { title: "Tangani Perlu Revisi", description: "Jika owner memilih Minta Revisi, buka filter Perlu Revisi, klik Edit & Ajukan, perbaiki data, lalu ajukan ulang." },
    ],
  }),
  workflow({
    faqNumber: 19,
    slug: "shopping-request",
    title: "Bagaimana cara membuat dan menyetujui Permohonan Belanja ke supplier?",
    aliases: ["buat permohonan belanja", "buat daftar belanja", "shopping request", "kebutuhan toko supplier", "setujui belanja supplier"],
    route: "/suppliers",
    actionLabel: "Buka Permohonan Belanja",
    iconKey: "list-plus",
    requiredCapabilities: [{ resource: "supplier", action: "create" }],
    steps: [
      { title: "Buka Supplier", description: "Masuk ke menu Supplier, lalu buka tab Permohonan Belanja." },
      { title: "Buat permohonan", description: "Klik Buat Permohonan Belanja. Pilih supplier wajib atau gunakan tambah supplier cepat." },
      { title: "Tambahkan produk", description: "Cari produk memakai thumbnail, isi kebutuhan, lalu pilih Stok Bersama atau Stok Produk Ini. Produk bergrup default ke Stok Bersama." },
      { title: "Periksa preview", description: "Periksa simulasi stok sebelum, sesudah, delta, dan varian terdampak, lalu klik Simpan Permohonan Belanja. Status menjadi Diajukan dan stok belum berubah." },
      { title: "Edit bila diperlukan", description: "Sebelum item pertama diputuskan, Owner atau role dengan izin supplier.shopping_request.edit:update dapat mengubah supplier, produk, jumlah kebutuhan, mode stok, dan catatan." },
      { title: "Isi Jumlah yang Di-ACC", description: "Owner atau role dengan izin supplier.shopping_request.set_approved_qty:update dapat memakai tombol terpisah atau mengisi langsung di modal Setujui Daftar Belanja. Kebutuhan Belanja ditampilkan sebagai pembanding dan input awal kosong bila belum disimpan. Pengguna tanpa izin quantity melihat nilai secara read-only." },
      { title: "Periksa approval", description: "Pengguna dengan izin supplier.shopping_request.approve_stock:update membuka Setujui, mengisi Jumlah yang Di-ACC bila juga berwenang, lalu memeriksa mode Stok Bersama atau Stok Produk Ini, live preview, dan Estimasi pengeluaran. Jumlah di atas kebutuhan memerlukan satu konfirmasi; item tanpa harga modal dihitung Rp0 dan diberi peringatan." },
      { title: "Putuskan per item atau sekaligus", description: "Klik Setujui Item untuk memproses satu item atau setujui semua item tersisa sekaligus. Jumlah yang baru diisi disimpan sebelum approval. Stok langsung berubah per item berdasarkan Jumlah yang Di-ACC; nilai 0 menjadi Tidak Disetujui tanpa mutasi stok. Item yang sudah diputuskan terkunci." },
      { title: "Periksa penyelesaian otomatis", description: "Permohonan tetap Diajukan selama masih ada item menunggu. Setelah item terakhir diproses, status selesai otomatis dan sistem membuat satu Pengeluaran kategori Bahan pada tanggal permohonan. Entri memakai badge Permohonan Belanja dan tidak dapat diedit atau dihapus dari Keuangan." },
    ],
  }),
  workflow({
    faqNumber: 20,
    slug: "record-expense",
    title: "Bagaimana cara mencatat pengeluaran operasional toko?",
    aliases: ["catat pengeluaran", "tambah pengeluaran", "expense toko", "biaya operasional"],
    route: "/keuangan",
    actionLabel: "Buka Keuangan",
    iconKey: "wallet-cards",
    requiredCapabilities: [{ resource: "expense", action: "create" }],
    steps: [
      { title: "Buka Keuangan", description: "Masuk ke sidebar Keuangan, lalu buka halaman Keuangan." },
      { title: "Tambah pengeluaran", description: "Klik tombol Tambah Pengeluaran untuk membuka form." },
      { title: "Isi nominal dan kategori", description: "Masukkan nominal, kategori, dan catatan pendukung bila diperlukan." },
      { title: "Pilih gambar bukti", description: "Jika ada foto nota, klik Pilih gambar bukti untuk mengunggahnya ke R2. Jika R2 gagal, gunakan input prnt.sc yang muncul sebagai fallback." },
      { title: "Simpan pengeluaran", description: "Periksa pratinjau lampiran dan klik Simpan." },
      { title: "Kenali sumber pengeluaran", description: "Badge Manual menandai input dari form. Sementara itu, badge Permohonan Belanja menandai entri otomatis yang tidak dapat diedit atau dihapus dari Keuangan." },
    ],
  }),
  workflow({
    faqNumber: 21,
    slug: "export-financial-report",
    title: "Bagaimana cara mengekspor Laporan Keuangan ke Excel atau PDF?",
    aliases: ["ekspor laporan keuangan", "export excel pdf", "unduh laporan", "laporan keuangan pdf"],
    route: "/financial-report",
    actionLabel: "Buka Laporan Keuangan",
    iconKey: "file-down",
    requiredCapabilities: [{ resource: "financial-report", action: "read" }],
    steps: [
      { title: "Buka Laporan Keuangan", description: "Masuk ke halaman Laporan Keuangan." },
      { title: "Klik Ekspor", description: "Di kanan atas halaman, klik tombol Ekspor." },
      { title: "Pilih format", description: "Pilih Excel untuk data tabel, termasuk revenue per kategori produk, atau PDF untuk dokumen siap cetak." },
      { title: "Pilih periode", description: "Tentukan Harian, Mingguan, atau Bulanan. Berkas akan mengikuti periode ekspor yang dipilih." },
      { title: "Gunakan perintah AI", description: "Minta Pak Teladan mengekspor laporan langsung. Jika periode dan format tidak disebutkan, sistem memakai 30 hari terakhir dan PDF." },
      { title: "Unduh file dan baca saran", description: "File muncul sebagai kartu di chat tanpa auto-download. Klik Download PDF/Excel saat siap; setelah berhasil tombol berubah menjadi Download ulang dan saran Pak Teladan dibuat dari angka laporan yang sama." },
      { title: "Minta analisis menyeluruh", description: "Untuk analisis keuangan, Pak Teladan memeriksa seluruh metrik laporan dalam satu periode—ringkasan, metode pembayaran, produk, kategori, sales, shift, kehilangan stok, dan tren—lalu memberi saran." },
      { title: "Pahami KPI biaya", description: "KPI Pengeluaran mencakup pengeluaran manual dan Permohonan Belanja. Laba Bersih (Estimasi) adalah Laba Kotor dikurangi seluruh pengeluaran dan bukan laporan laba akrual formal." },
    ],
  }),
  workflow({
    faqNumber: 22,
    slug: "store-profile",
    title: "Bagaimana cara mengubah informasi profil toko yang muncul di struk?",
    aliases: ["ubah info toko", "profil toko struk", "logo toko", "alamat struk"],
    route: "/settings",
    actionLabel: "Buka Info Toko",
    iconKey: "store",
    requiredCapabilities: [{ resource: "settings", action: "update" }],
    steps: [
      { title: "Buka Pengaturan", description: "Masuk ke Lainnya, lalu Pengaturan." },
      { title: "Pilih Info Toko", description: "Buka tab Info Toko." },
      { title: "Ubah profil", description: "Perbarui logo, nama toko, alamat, dan nomor telepon yang tampil di struk." },
      { title: "Simpan perubahan", description: "Klik Simpan jika semua data sudah benar." },
    ],
  }),
  workflow({
    faqNumber: 23,
    slug: "manage-rbac",
    title: "Bagaimana pemilik toko mengatur hak akses atau izin bagi role?",
    aliases: ["atur hak akses", "mengatur rbac", "izin kasir admin", "permission role"],
    route: "/settings",
    actionLabel: "Buka RBAC",
    iconKey: "shield-check",
    requiredPages: ["/settings"],
    requiredCapabilities: [{ resource: "rbac", action: "update" }],
    steps: [
      { title: "Buka tab RBAC", description: "Masuk ke Pengaturan lalu pilih tab RBAC. Tab ini hanya tersedia untuk OWNER." },
      { title: "Periksa ringkasan", description: "Lihat Ringkasan Role dan Matrix Modul untuk memahami akses tiap role." },
      { title: "Edit izin", description: "Sesuaikan Akses Halaman dan Aksi Resource untuk ADMIN, CASHIER, SALES, atau INVENTORY." },
      { title: "Review perubahan", description: "Klik Review & Simpan untuk melihat ringkasan perubahan." },
      { title: "Konfirmasi sensitif", description: "Jika menyentuh izin sensitif seperti finance, WhatsApp, HPP, RBAC, atau approval, lakukan konfirmasi tambahan sebelum simpan." },
    ],
  }),
  workflow({
    faqNumber: 24,
    slug: "job-order-status",
    title: "Bagaimana cara memperbarui status pengerjaan pesanan cetak?",
    aliases: ["ubah status job order", "kanban produksi", "pesanan cetak", "status produksi"],
    route: "/production",
    actionLabel: "Buka Produksi",
    iconKey: "kanban",
    requiredCapabilities: [{ resource: "production", action: "update" }],
    steps: [
      { title: "Buka Produksi", description: "Masuk ke menu Produksi untuk melihat papan Kanban." },
      { title: "Temukan kartu", description: "Cari kartu pesanan cetak yang ingin diperbarui." },
      { title: "Geser status", description: "Seret kartu ke tahapan Baru, Sedang Diproses, Siap Diambil, atau Selesai sesuai kondisi aktual." },
    ],
  }),
  workflow({
    faqNumber: 25,
    slug: "pickup-notification",
    title: "Bagaimana cara mengirim notifikasi pengambilan barang kepada pelanggan?",
    aliases: ["kirim notifikasi pengambilan", "whatsapp siap diambil", "pesanan siap diambil", "notifikasi pickup"],
    route: "/production",
    actionLabel: "Buka Produksi",
    iconKey: "message-circle",
    requiredCapabilities: [{ resource: "production", action: "update" }, { resource: "whatsapp", action: "create" }],
    steps: [
      { title: "Buka papan Kanban", description: "Masuk ke menu Produksi dan temukan pesanan pada kolom Siap Diambil." },
      { title: "Pilih tombol WhatsApp", description: "Klik tombol WhatsApp pada kartu pesanan tersebut." },
      { title: "Kirim notifikasi", description: "Sistem akan mengirim pesan pengambilan ke nomor pelanggan yang terdaftar sesuai alur aplikasi." },
    ],
  }),
  workflow({
    faqNumber: 26,
    slug: "manage-salespersons",
    title: "Bagaimana cara mengelola daftar anggota Sales?",
    aliases: ["kelola sales", "tambah sales", "anggota sales", "aktifkan sales"],
    route: "/salespersons",
    actionLabel: "Buka Tim Sales",
    iconKey: "users",
    requiredCapabilities: [{ resource: "salesperson", action: "update" }],
    steps: [
      { title: "Buka Tim Sales", description: "Masuk ke menu Tim Sales di sidebar." },
      { title: "Tambah anggota", description: "Klik Tambah Sales, isi nama anggota baru, lalu simpan." },
      { title: "Ubah anggota", description: "Gunakan tombol edit untuk mengubah nama sales." },
      { title: "Atur status aktif", description: "Gunakan toggle cepat untuk mengaktifkan atau menonaktifkan anggota. Hanya sales aktif yang muncul di POS." },
    ],
  }),
  workflow({
    faqNumber: 27,
    slug: "salesperson-history",
    title: "Bagaimana cara melihat riwayat transaksi yang ditangani Sales tertentu?",
    aliases: ["riwayat transaksi sales", "transaksi sales tertentu", "kontribusi sales", "detail sales"],
    route: "/salespersons",
    actionLabel: "Buka Tim Sales",
    iconKey: "history",
    requiredCapabilities: [{ resource: "salesperson", action: "read" }],
    steps: [
      { title: "Buka Tim Sales", description: "Masuk ke menu Tim Sales." },
      { title: "Pilih sales", description: "Klik baris atau kartu nama sales yang ingin diperiksa." },
      { title: "Baca rincian", description: "Panel profil akan menampilkan rincian sales dan maksimal 20 transaksi terbaru yang ditangani." },
    ],
  }),
  workflow({
    faqNumber: 28,
    slug: "inventory-day-session",
    title: "Bagaimana cara melakukan Check In dan Check Out bagi staf gudang?",
    aliases: ["check in inventaris", "check out inventaris", "day session gudang", "morning check"],
    route: "/inventory",
    actionLabel: "Buka Inventaris",
    iconKey: "calendar-check",
    requiredCapabilities: [{ resource: "inventory", action: "update" }],
    steps: [
      { title: "Buka Inventaris", description: "Masuk ke halaman Inventaris pada awal hari kerja." },
      { title: "Selesaikan Check In", description: "Isi Morning Check: risiko stok, hitung bahan produksi utama, dan checklist area kerja serta keselamatan." },
      { title: "Kerjakan tugas harian", description: "Setelah Check In selesai, tab Tugas terbuka untuk pekerjaan harian inventaris." },
      { title: "Mulai Check Out", description: "Di akhir hari, buka ringkasan sesi dan klik Check Out." },
      { title: "Penuhi syarat penutupan", description: "Pastikan tugas harian selesai. Pada Sabtu, pilih gambar bukti Proof Kebersihan untuk diunggah ke R2. Jika R2 gagal, gunakan input prnt.sc yang muncul." },
    ],
  }),
  workflow({
    faqNumber: 29,
    slug: "delivery-order-marking",
    title: "Bagaimana cara melakukan marking pada Surat Jalan?",
    aliases: ["marking surat jalan", "tandai surat jalan", "delivery order marking", "sj unmarked"],
    route: "/inventory",
    actionLabel: "Buka Surat Jalan Inventaris",
    iconKey: "clipboard-signature",
    requiredCapabilities: [{ resource: "surat_jalan", action: "update" }],
    steps: [
      { title: "Buka antrean Surat Jalan", description: "Di Inventaris, buka tab Ringkasan atau Transaksi lalu Surat Jalan." },
      { title: "Cari status UNMARKED", description: "Temukan Surat Jalan yang belum ditandai di antrean gudang." },
      { title: "Klik Marking", description: "Gunakan tombol Marking pada baris Surat Jalan tersebut." },
      { title: "Pilih status penanganan", description: "Pilih status seperti Selesai, Belum Dikirim, Perlu Tanda Tangan, Perlu Follow Up, Ditunda, atau Tidak Relevan." },
      { title: "Simpan catatan", description: "Isi catatan untuk status pengecualian, lalu klik Simpan. Check Out terblokir jika masih ada Surat Jalan UNMARKED." },
    ],
  }),
  workflow({
    faqNumber: 30,
    slug: "approve-stock-logs",
    title: "Bagaimana cara menyetujui atau menolak pengajuan mutasi/Log Stok?",
    aliases: [
      "approval stock logs",
      "menyetujui stock logs",
      "tolak log stok",
      "persetujuan stok masuk",
      "konfirmasi mutasi stok",
    ],
    route: "/inventory",
    actionLabel: "Buka Inventaris",
    iconKey: "shield-check",
    requiredCapabilities: [{ resource: "inventory.approve", action: "update" }],
    steps: [
      { title: "Buka Inventaris", description: "Buka menu samping (sidebar) sebelah kiri layar Anda, lalu klik menu Inventaris." },
      { title: "Pilih sub-tab Log Stok", description: "Klik tab Riwayat di navigasi atas, kemudian pilih sub-tab Log Stok. Atau klik langsung badge notifikasi oranye di sidebar jika ada." },
      { title: "Beri keputusan persetujuan", description: "Cari pengajuan yang berstatus Pending (kuning) di tabel. Klik Setuju (hijau) untuk mengesahkan stok, atau Tolak (merah) untuk membatalkannya." },
      { title: "Tulis alasan jika ditolak", description: "Jika Anda memilih untuk menolak pengajuan, ketik alasan penolakan pada kolom pop-up yang muncul, lalu konfirmasi penolakan." },
    ],
  }),
  workflow({
    faqNumber: 31,
    slug: "inventory-workflow",
    title: "Bagaimana alur kerja harian staf gudang (Inventory)?",
    aliases: [
      "alur kerja inventaris",
      "alur kerja staf gudang",
      "alur kerja inventory",
      "harian gudang",
      "tugas harian gudang",
    ],
    route: "/inventory",
    actionLabel: "Buka Inventaris",
    iconKey: "warehouse",
    requiredCapabilities: [
      { resource: "inventory", action: "update" },
      { resource: "inventory.out_log.verify", action: "update" },
    ],
    steps: [
      { title: "Verifikasi Log OUT Belum Diverifikasi", description: "Setelah Check In, buka tab Tugas lalu Tugas Harian dan klik Log OUT Belum Diverifikasi. Verifikasi ini mengecek kebenaran catatan Log OUT, bukan matching stok fisik." },
      { title: "Beri keputusan Log OUT", description: "Klik Setujui jika catatan sudah benar. Klik Perlu Koreksi jika produk, qty, alasan, atau catatan perlu diperbaiki; baris berubah warna dan badge menjadi Perlu Koreksi." },
      { title: "Ajukan koreksi bila perlu", description: "Pada baris Perlu Koreksi, gunakan tombol Koreksi untuk mengisi data yang benar. Koreksi menunggu approval maker-checker sebelum baris siap dicek ulang dan disetujui." },
      { title: "Matching Stok Harian", description: "Pukul 15:00-20:00 WIB, buka Matching Stok Harian. Klik input Stok Gudang per baris; indikator hijau berarti sesuai, merah berarti selisih, dan kuning berarti belum valid. Baris selisih wajib memakai catatan sebelum Submit Matching." },
      { title: "Input Penerimaan Barang", description: "Saat barang dari supplier datang, buka tab Transaksi lalu Penerimaan Barang. Pilih invoice daftar belanja, cek badge Sudah dibuat atau Sudah lengkap, isi kuantitas fisik, lalu Ajukan ke Owner." },
      { title: "Catat Barang Pecah/Rusak", description: "Jika ada barang rusak, pilih menu Input / Transaksi lalu Laporkan Barang Rusak untuk mencatat penyesuaian stok." },
    ],
  }),
  workflow({
    faqNumber: 32,
    slug: "cashier-workflow",
    title: "Bagaimana alur kerja harian staf Kasir?",
    aliases: [
      "alur kerja kasir",
      "tugas harian kasir",
      "operasional kasir",
      "harian kasir",
    ],
    route: "/pos",
    actionLabel: "Buka Kasir",
    iconKey: "shopping-cart",
    requiredCapabilities: [{ resource: "shift", action: "update" }, { resource: "transaction", action: "create" }],
    steps: [
      { title: "Mulai Shift Kasir", description: "Sebelum bertransaksi, buka menu Shift Kasir di kategori Lainnya, isi nominal modal kas awal di laci fisik, lalu klik Mulai Shift." },
      { title: "Layani Transaksi POS", description: "Buka menu Kasir (POS) di sidebar, pilih produk pesanan pelanggan, klik Bayar, input nominal uang, lalu cetak struk pembayaran." },
      { title: "Catat Pengeluaran Laci", description: "Jika ada pengeluaran kas darurat, klik ikon dompet Pengeluaran di bagian atas layar POS, isi nominal dan alasan, lalu Simpan." },
      { title: "Proses Transaksi Pending", description: "Cek transaksi bertanda pending (biru) di Riwayat. Klik Setuju/Tolak di kolom aksi, tentukan pembayaran, lalu konfirmasi." },
      { title: "Tutup Shift Kasir", description: "Di akhir hari kerja, klik profil Anda di pojok kanan atas, pilih Tutup Shift, hitung uang fisik laci, lalu klik Konfirmasi Akhiri Shift." },
    ],
  }),
  workflow({
    faqNumber: 33,
    slug: "sales-workflow",
    title: "Bagaimana alur kerja harian staf Sales?",
    aliases: [
      "alur kerja sales",
      "tugas harian sales",
      "operasional sales",
      "harian sales",
    ],
    route: "/pos",
    actionLabel: "Buka Kasir",
    iconKey: "users",
    requiredCapabilities: [{ resource: "transaction", action: "create" }],
    steps: [
      { title: "Melayani Pelanggan", description: "Sambut pelanggan dengan ramah dan bantu cari produk atau tanyakan kebutuhan barang yang mereka cari." },
      { title: "Pilih Produk di POS", description: "Buka menu Kasir (POS) di sidebar kiri, masukkan produk-produk pesanan pelanggan ke dalam keranjang belanja." },
      { title: "Kirim Permintaan Pembayaran", description: "Kirimkan detail tagihan pesanan pembeli melalui sistem untuk proses pembayaran." },
      { title: "Cetak Invoice Tagihan", description: "Cetak 2 rangkap invoice tagihan pesanan dari sistem sebagai tanda bukti pesanan resmi." },
      { title: "Serahkan Nota ke Pelanggan", description: "Berikan satu rangkap invoice kepada pelanggan sebagai rincian belanja mereka." },
      { title: "Serahkan Uang ke Kasir", description: "Menyerahkan rangkap invoice kedua beserta uang pembayaran dari pelanggan kepada Kasir untuk diproses (Checkout)." },
    ],
  }),
  workflow({
    faqNumber: 34,
    slug: "change-individual-stock",
    title: "Bagaimana cara mengubah stok individual produk lewat tombol \"Ubah Produk\"?",
    aliases: [
      "ubah stok individual",
      "ganti stok produk",
      "edit stok individual",
      "ubah produk untuk stok",
      "stok saat ini produk"
    ],
    route: "/products",
    actionLabel: "Buka Produk",
    iconKey: "package",
    requiredCapabilities: [{ resource: "product", action: "update" }],
    steps: [
      { title: "Buka menu katalog", description: "Masuk ke sidebar Katalog, lalu buka halaman Produk." },
      { title: "Cari produk", description: "Temukan produk yang ingin disesuaikan kuantitas stoknya pada daftar tabel produk." },
      { title: "Klik tombol Ubah Produk", description: "Klik ikon pensil (Ubah Produk) di kolom paling kanan pada baris produk yang dipilih." },
      { title: "Ubah data stok", description: "Cari kolom input 'Stok Saat Ini' pada formulir modal edit produk, lalu ketik jumlah stok yang baru." },
      { title: "Simpan produk", description: "Periksa kembali data Anda, lalu klik tombol Simpan Produk untuk menyimpan stok baru ke sistem." }
    ],
  }),
  workflow({
    faqNumber: 35,
    slug: "update-stok-massal-product-first",
    title: "Bagaimana cara memakai Update Stok untuk satu produk dan banyak produk?",
    aliases: [
      "update stok",
      "update stok satu produk",
      "update stok massal",
      "ubah banyak stok produk",
      "stok bersama",
      "stok produk ini",
      "bulk grup stok",
      "update stok grup dari produk"
    ],
    route: "/inventory",
    actionLabel: "Buka Inventaris",
    iconKey: "warehouse",
    requiredCapabilities: [{ resource: "inventory", action: "update" }],
    steps: [
      { title: "Buka Update Stok", description: "Masuk ke halaman Inventaris, lalu klik tombol Update Stok di sebelah Input / Transaksi." },
      { title: "Pilih jalur", description: "Pilih Satu Produk (Single) untuk update satu produk dengan tampilan ringkas, atau pilih Banyak Produk (Massal) untuk membuka workflow Update Stok Massal yang sudah ada." },
      { title: "Cari produk", description: "Di Satu Produk, cari dan pilih satu produk. Di Banyak Produk (Massal), gunakan pencarian produk untuk menambahkan setiap produk atau varian yang stoknya mau diubah. Thumbnail/foto produk tampil di hasil pencarian dan kartu pilihan agar barang mudah dicek." },
      { title: "Atur aksi dan jumlah", description: "Pilih Tambah stok, Kurangi stok, atau Set stok akhir. Untuk mode massal, setiap produk punya aksi, input stok, catatan, dan mode sendiri." },
      { title: "Pilih mode stok", description: "Pilih Stok Bersama untuk menghitung dampak ke stok grup dan varian lain. Pilih Stok Produk Ini jika hanya produk itu yang dibuatkan log stok dan stok grup tidak diubah." },
      { title: "Cek preview dan konflik", description: "Cek preview dengan foto produk/varian, lalu pastikan tidak ada produk duplikat. Jika dua varian dari grup yang sama sama-sama memakai Stok Bersama, ikuti pesan Pilih satu produk saja per grup stok untuk mode Stok Bersama." },
      { title: "Ajukan approval", description: "Klik submit untuk membuat pengajuan. Stok Bersama tampil sebagai bundle di Stock Log, sedangkan Stok Produk Ini menjadi log terpisah sampai approval selesai." },
    ],
  }),
  workflow({
    faqNumber: 36,
    slug: "export-customer-recap",
    title: "Bagaimana cara mengekspor rekap pelanggan per tipe ke Excel atau PDF?",
    aliases: ["ekspor rekap pelanggan", "export customer recap", "rekap pelanggan excel", "rekap pelanggan pdf", "analisis ai customer", "top produk pelanggan"],
    route: "/customers",
    actionLabel: "Buka Pelanggan",
    iconKey: "file-spreadsheet",
    requiredCapabilities: [{ resource: "customer", action: "read" }],
    steps: [
      { title: "Buka Rekap Pelanggan", description: "Masuk ke menu Pelanggan dan temukan bagian Rekap Pelanggan." },
      { title: "Klik Ekspor", description: "Klik tombol Ekspor pada header rekap." },
      { title: "Pilih periode", description: "Pilih Harian, Mingguan, Bulanan, atau Tahunan. Periode Mingguan berjalan dari Senin sampai hari ini." },
      { title: "Pilih format", description: "Pilih Excel (.xlsx) untuk sheet Agen, Umum, Pemerintah, Industri, dan Ringkasan, atau PDF untuk section per tipe dan halaman Ringkasan Semua Tipe." },
      { title: "Gunakan perintah AI", description: "Minta Pak Teladan mengekspor rekap pelanggan langsung. Jika periode dan format tidak disebutkan, sistem memakai 30 hari terakhir dan PDF." },
      { title: "Unduh file dan baca saran", description: "File muncul sebagai kartu di chat tanpa auto-download. Klik Download PDF/Excel saat siap; setelah berhasil tombol berubah menjadi Download ulang dan saran Pak Teladan memakai dataset rekap pelanggan yang sama." },
      { title: "Baca hasil", description: "Setiap tipe berisi tabel pelanggan yang diurutkan berdasarkan Total Belanja, Produk Favorit, dan Top 10 Produk. Sheet atau section Ringkasan berisi KPI serta 3-5 insight Analisis AI." },
    ],
  }),
  workflow({
    faqNumber: 37,
    slug: "notification-center",
    title: "Bagaimana cara membaca notifikasi penting dari sistem dan Pak Teladan?",
    aliases: [
      "baca notifikasi",
      "notifikasi belum dibaca",
      "badge merah notifikasi",
      "pak teladan kasih tahu notifikasi",
      "tandai semua dibaca",
      "notifikasi permohonan belanja",
    ],
    route: "/dashboard",
    actionLabel: "Buka Dashboard",
    iconKey: "bell",
    requiredPages: ["/dashboard"],
    requiredCapabilities: [],
    steps: [
      { title: "Lihat badge merah", description: "Ikon bell di kanan atas dan tombol Pak Teladan menampilkan badge merah berisi jumlah notifikasi yang belum dibaca." },
      { title: "Buka pusat notifikasi", description: "Klik ikon bell untuk melihat update terbaru seperti Persetujuan Transaksi, permintaan stok, dan Permohonan Belanja." },
      { title: "Buka detail", description: "Klik satu notifikasi untuk menandainya sebagai sudah dibaca dan langsung menuju halaman kerja yang terkait. Badge berkurang otomatis." },
      { title: "Bereskan semua", description: "Klik Tandai semua dibaca jika seluruh update sudah kamu review. Badge merah hilang ketika jumlah unread menjadi nol." },
      { title: "Cek heads-up Pak Teladan", description: "Buka Pak Teladan saat ada badge merah. Panel chat menampilkan sampai tiga notifikasi terbaru yang bisa langsung dibuka tanpa perlu mengetik pertanyaan." },
    ],
  }),
];

export function getWorkflowPayload(workflow: AssistantWorkflowDefinition): AssistantWorkflowPayload {
  return {
    id: workflow.id,
    title: workflow.title,
    route: workflow.route,
    actionLabel: workflow.actionLabel,
    sourceRef: workflow.sourceRef,
    steps: workflow.steps.map((step) => ({
      id: step.id,
      title: step.title,
      description: step.description,
      route: step.route,
      actionLabel: step.actionLabel,
      iconKey: step.iconKey,
    })),
  };
}
