import React from "react";
import { CalendarRange, ChevronLeft, ChevronRight, Download, Plus } from "lucide-react";

import { GuideTarget } from "../GuideTarget";
import { PreviewButton, PreviewField, PreviewMetric, PreviewModal, PreviewPageRoot } from "../PreviewPrimitives";
import type { PreviewContext } from "../types";

export function FinancePreview(ctx: PreviewContext) {
  const report = ctx.state === "finance-report";
  const formOpen = ctx.state === "finance-expense-form-open";
  return <PreviewPageRoot ctx={ctx} className="bg-surface-50"><GuideTarget ctx={ctx} target="finance-primary" className="min-h-[1040px]">{report ? <ReportView ctx={ctx} /> : <CashFlowView ctx={ctx} />}</GuideTarget>{formOpen ? <ExpenseModal ctx={ctx} /> : null}</PreviewPageRoot>;
}

function CashFlowView({ ctx }: { ctx: PreviewContext }) {
  return <><div className="flex items-center justify-between border-b border-surface-200 bg-white px-5 py-3"><div><h1 className="text-2xl font-bold">Keuangan</h1><p className="text-xs text-surface-500">Pemasukan & Pengeluaran</p></div><GuideTarget ctx={ctx} target="finance-date-filter" className="flex items-center gap-2 rounded-xl border bg-white p-1 shadow-sm"><span className="p-2"><ChevronLeft className="h-4 w-4" /></span><strong className="px-3 text-sm">Juli 2026</strong><span className="p-2 opacity-30"><ChevronRight className="h-4 w-4" /></span></GuideTarget></div><div className="mx-auto max-w-6xl space-y-4 px-4 py-4"><GuideTarget ctx={ctx} target="finance-summary" className="rounded-3xl border border-emerald-100 bg-gradient-to-br from-emerald-50 via-white to-white p-6 shadow-sm"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-surface-500">Net Cash Flow Juli 2026</p><p className="mt-2 text-5xl font-bold text-emerald-700">Rp42.680.000</p><p className="mt-2 text-xs text-surface-500">Rp58.420.000 pemasukan · Rp15.740.000 pengeluaran</p></div><PreviewButton ctx={ctx} target="finance-expense-create" tone="brand" icon={Plus}>Tambah Pengeluaran</PreviewButton></div></GuideTarget><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-sm font-semibold">Arus Kas Harian</h2><div className="mt-5 flex h-52 items-center justify-center border-b border-l border-surface-200"><div className="flex h-full w-full items-end gap-5 px-8">{[80,130,100,170,120,190,150].map((h,i) => <div key={i} className="flex flex-1 items-end gap-1"><span className="w-1/2 rounded-t bg-emerald-500" style={{height:h}} /><span className="w-1/2 rounded-t bg-red-500" style={{height:h*.45}} /></div>)}</div></div></section><div className="grid grid-cols-2 gap-4"><section className="rounded-2xl border bg-white shadow-sm"><h2 className="border-b p-4 text-sm font-semibold">Pemasukan</h2><p className="p-4 text-2xl font-bold text-emerald-700">Rp58.420.000</p>{['10 Jul · Rp8.250.000','09 Jul · Rp7.840.000','08 Jul · Rp6.120.000'].map((row) => <p key={row} className="border-t px-4 py-3 text-sm">{row}</p>)}</section><section className="rounded-2xl border bg-white shadow-sm"><h2 className="border-b p-4 text-sm font-semibold">Pengeluaran</h2><p className="p-4 text-2xl font-bold text-red-600">Rp15.740.000</p>{['Operasional · Rp3.200.000','Bahan · Rp8.480.000','Lainnya · Rp4.060.000'].map((row) => <p key={row} className="border-t px-4 py-3 text-sm">{row}</p>)}</section></div></div></>;
}

function ReportView({ ctx }: { ctx: PreviewContext }) {
  return <div className="px-6 py-4"><div className="flex items-end justify-between"><div><h1 className="text-xl font-bold">Laporan Keuangan</h1><p className="text-xs text-surface-500">Revenue, gross profit, pembayaran, piutang, dan selisih shift.</p></div><GuideTarget ctx={ctx} target="finance-export" className="inline-flex items-center gap-2 rounded-xl bg-brand-600 px-4 py-2.5 text-sm font-bold text-white"><Download className="h-4 w-4" />Ekspor</GuideTarget></div><GuideTarget ctx={ctx} target="finance-date-filter" className="mt-4 grid grid-cols-[1fr_1fr_auto] gap-3 rounded-2xl border bg-white p-4"><PreviewField label="Dari" value="01 Juli 2026" /><PreviewField label="Sampai" value="10 Juli 2026" /><span className="flex items-end gap-2 pb-3 text-sm"><CalendarRange className="h-4 w-4" />01–10 Jul 2026</span></GuideTarget><div className="mt-4 grid grid-cols-6 gap-3"><PreviewMetric label="Omzet" value="Rp58 jt" tone="blue" /><PreviewMetric label="Terkumpul" value="Rp52 jt" tone="emerald" /><PreviewMetric label="Laba Kotor" value="Rp24 jt" tone="emerald" /><PreviewMetric label="Margin" value="41,2%" tone="violet" /><PreviewMetric label="Outstanding DP" value="Rp6 jt" tone="amber" /><PreviewMetric label="Loss Stok" value="Rp840 rb" tone="red" /></div></div>;
}

function ExpenseModal({ ctx }: { ctx: PreviewContext }) {
  return <PreviewModal ctx={ctx} target="finance-expense-form" title="Form Pengeluaran"><div className="grid grid-cols-2 gap-4"><PreviewField label="Pemohon" value="Dewi" /><PreviewField label="Kategori" value="Operasional" /><PreviewField label="Nominal" value="Rp250.000" /><GuideTarget ctx={ctx} target="finance-proof-url"><PreviewField label="URL Lampiran" value="https://prnt.sc/bukti" /></GuideTarget><div className="col-span-2"><PreviewField label="Keterangan" value="Pembelian perlengkapan toko" /></div></div><div className="mt-5 flex justify-end"><GuideTarget ctx={ctx} target="finance-save" className="rounded-xl bg-brand-600 px-5 py-3 text-sm font-bold text-white">Simpan Pengeluaran</GuideTarget></div></PreviewModal>;
}

